### ISSUE TITLE
Peer design/code review

### ISSUE THREAD

**Issue by distillers86** [salamarche/DiscoverMusic#3]
# Design/Code Review 1

## Project:
Discover Music
### Developer:
Simone LaMarche
### Reviewer:
Tim Zschernitz
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.| I like that the problem statement is concise which will really benefit the average person's ability to grasp the purpose of the app without being overburdened with extra unnecessary details. I think just a bit more detail might be helpful here as well without expanding the scope beyond concise. The solution portion feels like it could use just a bit more detail, maybe even just one additional sentence. As someone unfamilar with Soundcloud, maybe just a bit more explanation as to how that API will be used. As in, "With the Soundcloud API, users will be able to search based on zip code" or "users will be shown local artists nearby their location". Basically just a highlevel touch on how the app will connect users to local artists. Also, one other minor thing, I think soundcloud is mispelled as "soundcould".|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. | Your wireframes are awesome! They're exactly what they're meant to be and really give a great early visual of how the app will be structured. Additionally, it might be helpful in the long run to also have just a simple flow chart for the app that shows how users will move through those pages which just might help identify if there are any gaps in the plan for the app so far.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>|Based on the SQL under design documents, looks like you've got a good reference table in there to link up users to artists with the artist engagement table. As a helpful visual, maybe just use the diagram option in Intellij to show a visual representation of the tables relationships to include in the documentation as well. |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage.|The code all looks good to me so far. Well structured and easy to navigate. The code it self is easy to follow and understand. Seems like you've made sure to test appropriate classes and methods. I'm thinking you might still be working on GenericDao tests though thought I'd mention in case it was missed that the getAll test doesn't seem to have any test code. Other than that, it appears you've accounted for testing throughout the created classes with methods that should be tested. |

**Comment by pawaitemadisoncollege** [comment]
@timzschernitz and @salamarche Just one thing to add to this, there are some sneaky System.out.printlns/stacktraces out there.  Instructor-provided code has built-in standards "violations"?  sorry :) 

<img width="1010" alt="Screen Shot 2021-02-28 at 6 09 17 PM" src="https://user-images.githubusercontent.com/13874466/109438584-42842300-79f0-11eb-86ff-190b160b0309.png">
