### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by AliviaK** [salamarche/DiscoverMusic#5]
My apologies on the late posting!

# Project: Discover Music
## Reviewer: Alivia Kleinfeldt

Item | Considerations | Comments/Suggestions
-- | -- | --
  |   | Reviewer comments and suggestions go here. Each item should have at least one "kudos" and two suggestions for improvement
Problem Statement | 1. Accurately describes project purpose 2. Is professional and free of typos, slang, etc. 3. Fully explains the problem and the solution 4. Is understandable by the average person | Great and compelling problem statement; it's been nearly impossible to discover local music during this time and I'm unaware of any dedicated apps for smaller artists so as a musician myself I am very excited for your app! I'd maybe add some more detail on what the app does specifically to connect users to new music or how they might expect to interact with the app. Small note but API may be above "average user" terminology understanding. 
Design Documentation | 1. Navigation/flow through the application is logical and easy to use. 2. The order in which values are displayed are logical and easy to understand/use 3. The order in which the form fields entered are logical and easy to understand/use 4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Very thorough and logical wireframes. I think it looks very cohesive and professional! Great wireframes as well. Overall great documentation and planning.
Data model/Database | 1. Everything on the screens and problem statement/flow is represented in the model 2. There is at least one 1-to-many relationship. 3. The model represents good database design |  1-to-many implemented, and GenericDao looks great. Only recommendation at the moment is a visual for representation of keys and relationships and such.
Code | 1. Proper Maven project structure is used 2. a .gitignore file for IntelliJ Java projects has been implemented 3. There is not any redundant or copy/paste code in the JSPs or classes 4. Classes are appropriately-sized (no monster classes) Property files are used appropriately: no hard-coded values 5. Logging statements are used rather than System.out.println and printStackTrace. 6. There are appropriate unit tests/code coverages. | Code and tests so far looks good; any redundant code is taken care of with GenericDao and test coverage looks good!

**Comment by pawaitemadisoncollege** [comment]
@salamarche and @AliviaK  A few sneaky printstack traces and printlns 

![Screen Shot 2021-03-06 at 2 52 31 PM](https://user-images.githubusercontent.com/13874466/110220510-bbb9c500-7e8b-11eb-9607-b0fc78f19d3b.png)
